unit Delphi.ORM.Attributes;

interface

uses System.Rtti;

type
  EntityAttribute = class(TCustomAttribute);

  TCustomNameAttribute = class(TCustomAttribute)
  private
    FName: String;
  public
    constructor Create(Name: String);

    property Name: String read FName;
  end;

  AutoGeneratedAttribute = class(TCustomAttribute);
  FieldNameAttribute = class(TCustomNameAttribute);
  ManyValueAssociationLinkNameAttribute = class(TCustomNameAttribute);
  PrimaryKeyAttribute = class(TCustomNameAttribute);
  SingleTableInheritanceAttribute = class(TCustomAttribute);
  TableNameAttribute = class(TCustomNameAttribute);

  DefaultValueAttribute = class(TCustomAttribute)
  private
    FValue: String;
  public
    constructor Create(const AValue: String);

    property Value: String read FValue;
  end;

implementation

uses System.SysUtils;

{ TCustomNameAttribute }

constructor TCustomNameAttribute.Create(Name: String);
begin
  inherited Create;

  FName := Name;
end;

{ DefaultValueAttribute }

constructor DefaultValueAttribute.Create(const AValue: String);
begin
  inherited Create;

  FValue := AValue;
end;

end.
