unit Persisto.Classes.Loader.Test;

interface

uses DUnitX.TestFramework, Persisto;

type
  [TestFixture]
  TClassLoaderTest = class
  private
    FManager: TManager;
    FManagerInsert: TManager;

    procedure InsertDatabaseData(const Connection: IDatabaseConnection);
  public
    [Setup]
    procedure Setup;
    [TearDown]
    procedure TearDown;
    [Test]
    procedure WhenSelectToOpenAnObjectFromDatabaseCantRaiseAnyError;
    [Test]
    procedure WhenLoadAnObjectMustCreateItWhenLoadFromDatabase;
    [Test]
    procedure WhenLoadAnObjectMustLoadTheFieldsOfTheObjectWithTheValueInTheDatabase;
    [Test]
    procedure WhenLoadAnObjectInheritedFromAnotherMustLoadTheFieldValueOfAllClassLevel;
    [Test]
    procedure WhenLoadAnObjectWithForeignKeyCantRaiseAnyError;
    [Test]
    procedure WhenLoadAnEmptyTableCantRaiseAnyError;
    [Test]
    procedure WhenLoadAnObjectWithForeignKeyMustCreateTheForeignKeyObject;
    [Test]
    procedure WhenLoadAnObjectWithForeignKeyMustLoadTheFieldValuesOfTheForeignKeyObjects;
    [Test]
    procedure WhenLoadAnObjectWithForeignKeyMustLoadAllLevelsOfForeignKey;
    [Test]
    procedure WhenLoadAnObjectWithCircularReferenceMustRaiseAnError;
    [Test]
    procedure WhenTheLoadedObjectAsTheSameKeyMustKeepTheSameObjectInstance;
    [Test]
    procedure WhenLoadAnObjectAndTryToUpdateTheObjectCantRaiseErrorOfForeignKeyObject;
    [Test]
    procedure WhenLoadAnObjectAndUpdateAFieldMustUpdateOnlyTheChangedField;
    [Test]
    procedure WhenTryToLoadASingleObjectFromAnEmptyTableCantRaiseAnyError;
    [Test]
    procedure WhenLoadAllObjectsMustReturnAllObjectsFromTheTable;
  end;

implementation

uses System.Generics.Collections, System.SysUtils, Persisto.Test.Connection, Persisto.Test.Entity;

{ TClassLoaderTest }

procedure TClassLoaderTest.InsertDatabaseData(const Connection: IDatabaseConnection);
var
  Objects: TArray<TObject>;

  procedure UpdateDatabase;
  begin
    for var AObject in Objects do
      FManagerInsert.Mapper.GetTable(AObject.ClassType);

    FManagerInsert.UpdateDatabaseSchema;

    for var AObject in Objects do
      FManagerInsert.Insert(AObject);
  end;

  procedure InsertObjects;
  begin
    var Object1 := TClassWithPrimaryKey.Create;
    Object1.Value := 1;

    var Object2 := TMyEntityInheritedFromSimpleClass.Create;
    Object2.AnotherProperty := 'abc';
    Object2.BaseProperty := 'def';
    Object2.SimpleProperty := 111;

    Objects := [Object1, Object2];
  end;

begin
  Objects := nil;

  FManagerInsert.Mapper.GetTable(TInsertTestWithForeignKeyMoreOne);

  InsertObjects;

  UpdateDatabase;
end;

procedure TClassLoaderTest.Setup;
begin
  var Connection := CreateConnection;
  FManager := TManager.Create(Connection, CreateDialect);
  FManagerInsert := TManager.Create(Connection, CreateDialect);

  InsertDatabaseData(Connection);
end;

procedure TClassLoaderTest.TearDown;
begin
  FManager.Free;

  FManagerInsert.Free;
end;

procedure TClassLoaderTest.WhenLoadAllObjectsMustReturnAllObjectsFromTheTable;
begin
  FManagerInsert.Insert(TInsertAutoGenerated.Create);
  FManagerInsert.Insert(TInsertAutoGenerated.Create);
  FManagerInsert.Insert(TInsertAutoGenerated.Create);

  var Objects := FManager.Select.All.From<TInsertAutoGenerated>.Open.All;

  Assert.AreEqual<NativeInt>(3, Length(Objects));
end;

procedure TClassLoaderTest.WhenLoadAnEmptyTableCantRaiseAnyError;
begin
  Assert.WillNotRaise(
    procedure
    begin
      FManager.Select.All.From<TInsertTestWithForeignKey>.Open.One;
    end);
end;

procedure TClassLoaderTest.WhenLoadAnObjectAndTryToUpdateTheObjectCantRaiseErrorOfForeignKeyObject;
begin
  var AObject := TInsertAutoGenerated.Create;

  FManagerInsert.Insert(AObject);

  AObject := FManager.Select.All.From<TInsertAutoGenerated>.Open.One;

  Assert.WillNotRaise(
    procedure
    begin
      FManager.Update(AObject);
    end, EForeignObjectNotAllowed);
end;

procedure TClassLoaderTest.WhenLoadAnObjectAndUpdateAFieldMustUpdateOnlyTheChangedField;
begin
  var AObject := TInsertAutoGenerated.Create;
  AObject.Value := 111;

  FManagerInsert.Insert(AObject);

  AObject := FManager.Select.All.From<TInsertAutoGenerated>.Open.One;
  AObject.DateTime := EncodeDate(2023, 01, 01);

  FManager.ExectDirect('update InsertAutoGenerated set Value = 222');

  FManager.Update(AObject);

  var Cursor := FManager.OpenCursor('select Value from InsertAutoGenerated');

  Cursor.Next;

  Assert.AreEqual(222, Integer(Cursor.GetFieldValue(0)));
end;

procedure TClassLoaderTest.WhenLoadAnObjectInheritedFromAnotherMustLoadTheFieldValueOfAllClassLevel;
begin
  var AObject := FManager.Select.All.From<TMyEntityInheritedFromSimpleClass>.Open.One;

  Assert.AreEqual('abc', AObject.AnotherProperty);
  Assert.AreEqual('def', AObject.BaseProperty);
  Assert.AreEqual(111, AObject.SimpleProperty);
  Assert.AreEqual(10, AObject.Id);
end;

procedure TClassLoaderTest.WhenLoadAnObjectMustCreateItWhenLoadFromDatabase;
begin
  var AObject := FManager.Select.All.From<TClassWithPrimaryKey>.Open.One;

  Assert.IsNotNull(AObject);
end;

procedure TClassLoaderTest.WhenLoadAnObjectMustLoadTheFieldsOfTheObjectWithTheValueInTheDatabase;
begin
  var AObject := FManager.Select.All.From<TClassWithPrimaryKey>.Open.One;

  Assert.AreEqual(35, AObject.Id);
  Assert.AreEqual(1, AObject.Value);
end;

procedure TClassLoaderTest.WhenLoadAnObjectWithCircularReferenceMustRaiseAnError;
begin
  Assert.WillRaise(
    procedure
    begin
      FManager.Select.All.From<TClassRecursiveFirst>.Open.One;
    end, ERecursionSelectionError);
end;

procedure TClassLoaderTest.WhenLoadAnObjectWithForeignKeyCantRaiseAnyError;
begin
  Assert.WillNotRaise(
    procedure
    begin
      FManager.Select.All.From<TInsertTestWithForeignKey>.Open.One;
    end);
end;

procedure TClassLoaderTest.WhenLoadAnObjectWithForeignKeyMustCreateTheForeignKeyObject;
begin
  var &Object := TInsertTestWithForeignKey.Create;
  &Object.FK1 := TInsertAutoGenerated.Create;
  &Object.FK2 := TInsertAutoGenerated.Create;

  FManagerInsert.Insert(&Object);

  &Object := FManager.Select.All.From<TInsertTestWithForeignKey>.Open.One;

  Assert.IsNotNull(&Object.FK1);
  Assert.IsNotNull(&Object.FK2);
end;

procedure TClassLoaderTest.WhenLoadAnObjectWithForeignKeyMustLoadAllLevelsOfForeignKey;
begin
  var &Object := TInsertTestWithForeignKeyMoreOne.Create;
  &Object.FK := TInsertTestWithForeignKey.Create;
  &Object.FK.FK1 := TInsertAutoGenerated.Create;
  &Object.FK.FK1.Value := 111;
  &Object.FK.FK2 := TInsertAutoGenerated.Create;
  &Object.FK.FK2.Value := 222;

  FManagerInsert.Insert(&Object);

  Assert.WillNotRaise(
    procedure
    begin
      &Object := &FManager.Select.All.From<TInsertTestWithForeignKeyMoreOne>.Open.One;
    end);

  Assert.IsNotNull(&Object.FK);
  Assert.IsNotEmpty(&Object.FK.FK1.Id);
  Assert.IsTrue(&Object.FK.FK1.DateTime > 0);
  Assert.AreEqual(111, &Object.FK.FK1.Value);
  Assert.IsNotEmpty(&Object.FK.FK2.Id);
  Assert.IsTrue(&Object.FK.FK2.DateTime > 0);
  Assert.AreEqual(222, &Object.FK.FK2.Value);
end;

procedure TClassLoaderTest.WhenLoadAnObjectWithForeignKeyMustLoadTheFieldValuesOfTheForeignKeyObjects;
begin
  var &Object := TInsertTestWithForeignKey.Create;
  &Object.FK1 := TInsertAutoGenerated.Create;
  &Object.FK1.Value := 111;
  &Object.FK2 := TInsertAutoGenerated.Create;
  &Object.FK2.Value := 222;

  FManagerInsert.Insert(&Object);

  &Object := FManager.Select.All.From<TInsertTestWithForeignKey>.Open.One;

  Assert.IsNotEmpty(&Object.FK1.Id);
  Assert.IsTrue(&Object.FK1.DateTime > 0);
  Assert.AreEqual(111, &Object.FK1.Value);
  Assert.IsNotEmpty(&Object.FK2.Id);
  Assert.IsTrue(&Object.FK2.DateTime > 0);
  Assert.AreEqual(222, &Object.FK2.Value);
end;

procedure TClassLoaderTest.WhenSelectToOpenAnObjectFromDatabaseCantRaiseAnyError;
begin
  Assert.WillNotRaise(
    procedure
    begin
      FManager.Select.All.From<TClassWithPrimaryKey>.Open.One;
    end);
end;

procedure TClassLoaderTest.WhenTheLoadedObjectAsTheSameKeyMustKeepTheSameObjectInstance;
begin
  var &Object := TInsertTestWithForeignKey.Create;
  &Object.FK1 := TInsertAutoGenerated.Create;
  &Object.FK2 := &Object.FK1;

  FManagerInsert.Insert(&Object);

  &Object := &FManager.Select.All.From<TInsertTestWithForeignKey>.Open.One;

  Assert.AreSame(&Object.FK1, &Object.FK2);
end;

procedure TClassLoaderTest.WhenTryToLoadASingleObjectFromAnEmptyTableCantRaiseAnyError;
begin
  Assert.WillNotRaise(
    procedure
    begin
      FManager.Select.All.From<TInsertTestWithForeignKey>.Open.One;
    end);
end;

end.

