unit Persisto.SQLite.Test;

interface

uses DUnitX.TestFramework, Persisto, Persisto.Mapping, Persisto.SQLite;

type
  [TestFixture]
  TManipulatorSQLiteTest = class
  private
    FMetadataManipulator: TManipulatorSQLite;
  public
    [Setup]
    procedure Setup;
    [TearDown]
    procedure TearDown;
    [TestCase('Bigint', 'tkInt64,bigint')]
    [TestCase('Char', 'tkWChar,char')]
    [TestCase('Enumerator', 'tkEnumeration,tinyint')]
    [TestCase('Int', 'tkInteger,int')]
    [TestCase('Numeric', 'tkFloat,numeric')]
    [TestCase('Varchar', 'tkUString,varchar')]
    procedure TheFieldTypeFunctionMustReturnTheTypeHasExpected(const FieldType: TTypeKind; const FieldTypeComparision: String);
    [TestCase('Date', 'stDate,date')]
    [TestCase('DateTime', 'stDateTime,datetime')]
    [TestCase('Time', 'stTime,time')]
    [TestCase('Text', 'stText,text')]
    [TestCase('Boolean', 'stBoolean,bit')]
    [TestCase('Unique Identifier', 'stUniqueIdentifier,unique')]
    procedure TheSpecialFieldTypeFunctionMustReturnTheTypeHasExpected(const SpecialType: TDatabaseSpecialType; const SpecialTypeComparision: String);
    [TestCase('Date', 'agtCurrentDate,CURRENT_DATE')]
    [TestCase('Time', 'agtCurrentTime,CURRENT_TIME')]
    [TestCase('Date and Time', 'agtCurrentDateTime,CURRENT_TIMESTAMP')]
    [TestCase('Unique Identifier', 'agtNewUniqueIdentifier,UUID()')]
    [TestCase('GUID', 'agtNewGuid,GUID()')]
    [TestCase('Fixed Value', 'agtFixedValue,123')]
    procedure TheDefaultValueMustBeReturnedAsExpected(const DefaultType: TAutoGeneratedType; const DefaultTypeComparision: String);
  end;

  [TestFixture]
  TDialectSQLiteTest = class
  public
    [Test]
    procedure WhenCallCreateManipulatorMustReturnTheInstance;
  end;

implementation

uses System.SysUtils, System.Rtti;

{ TManipulatorSQLiteTest }

procedure TManipulatorSQLiteTest.Setup;
begin
  FMetadataManipulator := TManipulatorSQLite.Create(nil);
end;

procedure TManipulatorSQLiteTest.TearDown;
begin
  FMetadataManipulator.Free;
end;

procedure TManipulatorSQLiteTest.TheDefaultValueMustBeReturnedAsExpected(const DefaultType: TAutoGeneratedType; const DefaultTypeComparision: String);
begin
  var DefaultConstraint := TDefaultConstraint.Create;
  DefaultConstraint.AutoGeneratedType := DefaultType;
  DefaultConstraint.FixedValue := '123';
  var Manipulator := TManipulatorSQLite.Create(nil);

  Assert.AreEqual(DefaultTypeComparision, Manipulator.GetAutoGeneratedValue(DefaultConstraint));

  Manipulator.Free;

  DefaultConstraint.Free;
end;

procedure TManipulatorSQLiteTest.TheFieldTypeFunctionMustReturnTheTypeHasExpected(const FieldType: TTypeKind; const FieldTypeComparision: String);
begin
  var Context := TRttiContext.Create;
  var Field := TField.Create(nil);
  var Manipulator := TManipulatorSQLite.Create(nil);

  case FieldType of
    tkEnumeration: Field.FieldType := Context.GetType(TypeInfo(TDatabaseSpecialType));
    tkFloat: Field.FieldType := Context.GetType(TypeInfo(Double));
    tkInteger: Field.FieldType := Context.GetType(TypeInfo(Integer));
    tkInt64: Field.FieldType := Context.GetType(TypeInfo(Int64));
    tkUString: Field.FieldType := Context.GetType(TypeInfo(String));
    tkWChar: Field.FieldType := Context.GetType(TypeInfo(Char));
    else raise Exception.Create('Type not mapped!');
  end;

  Assert.AreEqual(FieldTypeComparision, Manipulator.GetFieldType(Field));

  Context.Free;

  Field.Free;

  Manipulator.Free;
end;

procedure TManipulatorSQLiteTest.TheSpecialFieldTypeFunctionMustReturnTheTypeHasExpected(const SpecialType: TDatabaseSpecialType; const SpecialTypeComparision: String);
begin
  var Field := TField.Create(nil);
  Field.SpecialType := SpecialType;
  var Manipulator := TManipulatorSQLite.Create(nil);

  Assert.AreEqual(SpecialTypeComparision, Manipulator.GetSpecialFieldType(Field));

  Field.Free;

  Manipulator.Free;
end;

{ TDialectSQLiteTest }

procedure TDialectSQLiteTest.WhenCallCreateManipulatorMustReturnTheInstance;
begin
  var Dialect := TDialectSQLite.Create as IDatabaseDialect;

  Assert.IsNotNull(Dialect.CreateManipulator(nil));
end;

end.

